In [57]:
import pandas as pd
train = pd.read_csv("train.csv",delimiter='\t')
test = pd.read_csv("test.csv",delimiter='\t')

In [58]:
train

link  \
0       /fa/news/6276899/اسفراین-جولانگاه-مقدونیان-تصا...   
1       /fa/news/4626291/اجرای-قطعات-سلام-آقا-بدون-انگ...   
2       /fa/news/4632846/حکایت-سیاریحون-از-نهضت-میرزا-...   
3       /fa/news/5058438/گفتگو-با-کارگردان-سریال-شهید-...   
4       /fa/news/6668241/گزارش-تصویری-مراسم-عزاداری-شب...   
...                                                   ...   
117187  /fa/news/5987093/پرسپولیس-ایران-الهلال-عربستان...   
117188  /fa/news/4800268/شیاپ-چانگ-انتخابی-برای-پومسه-...   
117189  /fa/news/5470894/منچستریونایتد-مذاکره-با-گوارد...   
117190  /fa/news/6637446/نویمایر-آلمانی-آری-جپاروف-ازب...   
117191  /fa/news/5727671/برنامه-روز-هفتم-مسابقات-المپی...   

                                                    title        code_news  \
0                     اسفراین؛ جولانگاه مقدونیان + تصاویر  کد خبر: ۶۲۷۶۸۹۹   
1       اجرای قطعات "سلام آقا" بدون انگیزه مالی و با ا...  کد خبر: ۴۶۲۶۲۹۱   
2       حکایت "سیاریحون" از نهضت میرزا کوچک خان جنگلی ...  کد خبر: ۴۶۳۲۸۴۶   
3       گفتگو با کارگردان سریال شهید مدرس/قدرت بیان فو...  کد خبر: ۵۰۵۸۴۳۸   
4       گزارش تصویری مراسم عزاداری شب ششم محرم ۹۷/ حضو...  کد خبر: ۶۶۶۸۲۴۱   
...                                                   ...              ...   
117187  پرسپولیس ایران _ الهلال عربستان/ پرتماشاگرترین...  کد خبر: ۵۹۸۷۰۹۳   
117188                 شیاپ چانگ انتخابی برای پومسه رو ها  کد خبر: ۴۸۰۰۲۶۸   
117189     منچستریونایتد مذاکره با گواردیولا را تکذیب کرد  کد خبر: ۵۴۷۰۸۹۴   
117190  نویمایر آلمانی آری جپاروف ازبک خیر/منطق قراردا...  کد خبر: ۶۶۳۷۴۴۶   
117191                 برنامه روز هفتم مسابقات المپیک ریو  کد خبر: ۵۷۲۷۶۷۱   

           category                                   date  \
0       فرهنگی هنری      تاریخ انتشار: ۲۱ مهر ۱۳۹۶ - ۰۷:۰۴   
1       فرهنگی هنری     تاریخ انتشار: ۱۹ آبان ۱۳۹۲ - ۱۰:۰۰   
2       فرهنگی هنری     تاریخ انتشار: ۲۵ آبان ۱۳۹۲ - ۱۳:۴۵   
3       فرهنگی هنری      تاریخ انتشار: ۱۰ آذر ۱۳۹۳ - ۱۰:۵۴   
4       فرهنگی هنری   تاریخ انتشار: ۲۵ شهريور ۱۳۹۷ - ۱۰:۳۵   
...             ...                                    ...   
117187        ورزشی    تاریخ انتشار: ۰۳ اسفند ۱۳۹۵ - ۱۰:۰۰   
117188        ورزشی  تاریخ انتشار: ۲۲ فروردين ۱۳۹۳ - ۱۳:۳۷   
117189        ورزشی     تاریخ انتشار: ۰۳ بهمن ۱۳۹۴ - ۰۴:۱۶   
117190        ورزشی      تاریخ انتشار: ۰۸ مهر ۱۳۹۷ - ۱۴:۳۳   
117191        ورزشی    تاریخ انتشار: ۱۹ مرداد ۱۳۹۵ - ۱۰:۱۲   

                                                     text  
0        به گزارش خبرنگار حوزه میراث و گردشگری گروه فر...  
1        به گزارش حوزه موسیقی باشگاه خبرنگاران، مهدی ی...  
2        به گزارش حوزه تئاتر باشگاه خبرنگاران به نقل ا...  
3        به گزارش خبرنگار رادیو تلویزیون باشگاه خبرنگا...  
4        به گزارش خبرنگار تکیه حسینی گروه فرهنگی باشگا...  
...                                                   ...  
117187   به گزارش\r\nخبرنگار حوزه فوتبال و فوتسال گروه...  
117188   به گزارش خبرنگار\r\nورزشی باشگاه خبرنگاران؛ ر...  
117189                                                NaN  
117190   به گزارش  خبرنگار فوتبال و فوتسال گروه ورزشی ...  
117191   *برنامه رقابت های  ملی پوشان کاروان ایران : گ...  

[117192 rows x 6 columns]

In [59]:
train.shape

(117192, 6)

In [60]:
test.shape

(21104, 6)

In [61]:
from collections import Counter
import numpy as np
import re

In [62]:
class DataPreprocessor:
    def __init__(self,data):
        self.data=data
        self.cleaned_data=self.clean(self.data)
        self.dict_chars,self.unique_chars,self.all_chars=self.count_chars(self.cleaned_data)
        self.char2index,self.index2char=self.tokenize()
    def clean(self,data):
        data.dropna(subset=['text'],inplace= True)
        cleaned_data=[]
        for i in data["text"]:
            st=re.sub(r"[^۰-۹\ژ\ز\ر\ذ\د\خ\ح\چ\ج\ث\ت\ب\پ\ا\.\؟\س\ش\ص\ض\ط\ظ\ع\غ\ف\ق\ک\گ\ل\م\ن\و\ه\ی\آ]"," ",i)
            st=re.sub(r"[۰-۹]+","N",st)
            st="s" + st + "e"
            cleaned_data.append(st)
        cleaned_data=pd.DataFrame({'text':cleaned_data})
        return cleaned_data
    def count_chars(self,cleaned_data):
        chars=[]
        for i in cleaned_data["text"]:
            for j in i:
                chars.append(j)
        count=Counter(chars)
        unique_chars=len(count.keys())
        all_chars=sum(count.values())
        return count,unique_chars,all_chars
    def tokenize(self):
        list=[]
        for key in self.dict_chars.keys():
            list.append(key)
        list2=[]
        list3=[]
        for i in range(len(list)):
            list2.append((list[i],i))
            list3.append((i,list[i]))
        char2index=dict(list2)
        index2char=dict(list3)
        return char2index,index2char
    def char_to_index(self,string):
        list4=[]
        for m in string:
            if(m in self.char2index.keys()):
                list4.append(self.char2index.get(m))
            else:
                list4.append(-1)
        return list4
    def index_to_char(self,numbers):
        st=""
        for n in numbers:
            if(n in self.index2char.keys()):
                st=st+self.index2char.get(n)
            else:
                st=st+' '
        return st         

In [63]:
object1=DataPreprocessor(train)

In [64]:
object1.data

link  \
0       /fa/news/6276899/اسفراین-جولانگاه-مقدونیان-تصا...   
1       /fa/news/4626291/اجرای-قطعات-سلام-آقا-بدون-انگ...   
2       /fa/news/4632846/حکایت-سیاریحون-از-نهضت-میرزا-...   
3       /fa/news/5058438/گفتگو-با-کارگردان-سریال-شهید-...   
4       /fa/news/6668241/گزارش-تصویری-مراسم-عزاداری-شب...   
...                                                   ...   
117182   /fa/news/6513525/منتخب-لحظات-برتر-اینیستا-فیلم\n   
117187  /fa/news/5987093/پرسپولیس-ایران-الهلال-عربستان...   
117188  /fa/news/4800268/شیاپ-چانگ-انتخابی-برای-پومسه-...   
117190  /fa/news/6637446/نویمایر-آلمانی-آری-جپاروف-ازب...   
117191  /fa/news/5727671/برنامه-روز-هفتم-مسابقات-المپی...   

                                                    title        code_news  \
0                     اسفراین؛ جولانگاه مقدونیان + تصاویر  کد خبر: ۶۲۷۶۸۹۹   
1       اجرای قطعات "سلام آقا" بدون انگیزه مالی و با ا...  کد خبر: ۴۶۲۶۲۹۱   
2       حکایت "سیاریحون" از نهضت میرزا کوچک خان جنگلی ...  کد خبر: ۴۶۳۲۸۴۶   
3       گفتگو با کارگردان سریال شهید مدرس/قدرت بیان فو...  کد خبر: ۵۰۵۸۴۳۸   
4       گزارش تصویری مراسم عزاداری شب ششم محرم ۹۷/ حضو...  کد خبر: ۶۶۶۸۲۴۱   
...                                                   ...              ...   
117182                    منتخب لحظات برتر اینیستا + فیلم  کد خبر: ۶۵۱۳۵۲۵   
117187  پرسپولیس ایران _ الهلال عربستان/ پرتماشاگرترین...  کد خبر: ۵۹۸۷۰۹۳   
117188                 شیاپ چانگ انتخابی برای پومسه رو ها  کد خبر: ۴۸۰۰۲۶۸   
117190  نویمایر آلمانی آری جپاروف ازبک خیر/منطق قراردا...  کد خبر: ۶۶۳۷۴۴۶   
117191                 برنامه روز هفتم مسابقات المپیک ریو  کد خبر: ۵۷۲۷۶۷۱   

           category                                    date  \
0       فرهنگی هنری       تاریخ انتشار: ۲۱ مهر ۱۳۹۶ - ۰۷:۰۴   
1       فرهنگی هنری      تاریخ انتشار: ۱۹ آبان ۱۳۹۲ - ۱۰:۰۰   
2       فرهنگی هنری      تاریخ انتشار: ۲۵ آبان ۱۳۹۲ - ۱۳:۴۵   
3       فرهنگی هنری       تاریخ انتشار: ۱۰ آذر ۱۳۹۳ - ۱۰:۵۴   
4       فرهنگی هنری    تاریخ انتشار: ۲۵ شهريور ۱۳۹۷ - ۱۰:۳۵   
...             ...                                     ...   
117182        ورزشی  تاریخ انتشار: ۰۵ ارديبهشت ۱۳۹۷ - ۲۱:۲۸   
117187        ورزشی     تاریخ انتشار: ۰۳ اسفند ۱۳۹۵ - ۱۰:۰۰   
117188        ورزشی   تاریخ انتشار: ۲۲ فروردين ۱۳۹۳ - ۱۳:۳۷   
117190        ورزشی       تاریخ انتشار: ۰۸ مهر ۱۳۹۷ - ۱۴:۳۳   
117191        ورزشی     تاریخ انتشار: ۱۹ مرداد ۱۳۹۵ - ۱۰:۱۲   

                                                     text  
0        به گزارش خبرنگار حوزه میراث و گردشگری گروه فر...  
1        به گزارش حوزه موسیقی باشگاه خبرنگاران، مهدی ی...  
2        به گزارش حوزه تئاتر باشگاه خبرنگاران به نقل ا...  
3        به گزارش خبرنگار رادیو تلویزیون باشگاه خبرنگا...  
4        به گزارش خبرنگار تکیه حسینی گروه فرهنگی باشگا...  
...                                                   ...  
117182   به گزارش گروه فیلم و صوت باشگاه خبرنگاران جوا...  
117187   به گزارش\r\nخبرنگار حوزه فوتبال و فوتسال گروه...  
117188   به گزارش خبرنگار\r\nورزشی باشگاه خبرنگاران؛ ر...  
117190   به گزارش  خبرنگار فوتبال و فوتسال گروه ورزشی ...  
117191   *برنامه رقابت های  ملی پوشان کاروان ایران : گ...  

[97030 rows x 6 columns]

In [65]:
cleaned_data=object1.cleaned_data
cleaned_data

text
0      s به گزارش خبرنگار حوزه میراث و گردشگری گروه ف...
1      s به گزارش حوزه موسیقی باشگاه خبرنگاران  مهدی ...
2      s به گزارش حوزه ت اتر باشگاه خبرنگاران به نقل ...
3      s به گزارش خبرنگار رادیو تلویزیون باشگاه خبرنگ...
4      s به گزارش خبرنگار تکیه حسینی گروه فرهنگی باشگ...
...                                                  ...
97025  s به گزارش گروه فیلم و صوت باشگاه خبرنگاران جو...
97026  s به گزارش  خبرنگار حوزه فوتبال و فوتسال گروه ...
97027  s به گزارش خبرنگار  ورزشی باشگاه خبرنگاران  رق...
97028  s به گزارش  خبرنگار فوتبال و فوتسال گروه ورزشی...
97029  s  برنامه رقابت های  ملی پوشان کاروان ایران   ...

[97030 rows x 1 columns]

In [66]:
cleaned_data=cleaned_data["text"].str.cat(sep=' ')

In [67]:
cleaned_data[:200]

's به گزارش خبرنگار حوزه میراث و گردشگری گروه فرهنگی باشگاه خبرنگاران جوان  محمد حسن خان اعتماد السلطنه به نقل از برخی منابع  اسفراین  را چمن کالپوش دانسته است. چمن کالپوش بر اساس آنچه در اعتقادات اهال'

In [68]:
object1.dict_chars

Counter({'s': 97030,
         ' ': 47443628,
         'ب': 5560834,
         'ه': 7812715,
         'گ': 1941309,
         'ز': 2755953,
         'ا': 19294844,
         'ر': 11221534,
         'ش': 3258093,
         'خ': 1596153,
         'ن': 8749660,
         'ح': 1256529,
         'و': 7352556,
         'م': 7149615,
         'ی': 10751361,
         'ث': 165995,
         'د': 8605850,
         'ف': 1803107,
         'ج': 1406612,
         'س': 3962124,
         'ع': 1595400,
         'ت': 6155048,
         'ل': 3480712,
         'ط': 639410,
         'ق': 1419533,
         'چ': 366094,
         'ک': 3087117,
         'پ': 862128,
         '.': 1040558,
         'آ': 800641,
         'غ': 235077,
         'N': 115757,
         'ذ': 230921,
         'ظ': 265260,
         'ص': 814177,
         'e': 97030,
         '؟': 21428,
         'ض': 379264,
         'ژ': 123819})

In [69]:
unique_chars=object1.unique_chars
unique_chars

39

In [70]:
all_chars=object1.all_chars
all_chars

173914876

In [71]:
char2index=object1.char2index
char2index

{'s': 0,
 ' ': 1,
 'ب': 2,
 'ه': 3,
 'گ': 4,
 'ز': 5,
 'ا': 6,
 'ر': 7,
 'ش': 8,
 'خ': 9,
 'ن': 10,
 'ح': 11,
 'و': 12,
 'م': 13,
 'ی': 14,
 'ث': 15,
 'د': 16,
 'ف': 17,
 'ج': 18,
 'س': 19,
 'ع': 20,
 'ت': 21,
 'ل': 22,
 'ط': 23,
 'ق': 24,
 'چ': 25,
 'ک': 26,
 'پ': 27,
 '.': 28,
 'آ': 29,
 'غ': 30,
 'N': 31,
 'ذ': 32,
 'ظ': 33,
 'ص': 34,
 'e': 35,
 '؟': 36,
 'ض': 37,
 'ژ': 38}

In [72]:
index2char=object1.index2char
index2char

{0: 's',
 1: ' ',
 2: 'ب',
 3: 'ه',
 4: 'گ',
 5: 'ز',
 6: 'ا',
 7: 'ر',
 8: 'ش',
 9: 'خ',
 10: 'ن',
 11: 'ح',
 12: 'و',
 13: 'م',
 14: 'ی',
 15: 'ث',
 16: 'د',
 17: 'ف',
 18: 'ج',
 19: 'س',
 20: 'ع',
 21: 'ت',
 22: 'ل',
 23: 'ط',
 24: 'ق',
 25: 'چ',
 26: 'ک',
 27: 'پ',
 28: '.',
 29: 'آ',
 30: 'غ',
 31: 'N',
 32: 'ذ',
 33: 'ظ',
 34: 'ص',
 35: 'e',
 36: '؟',
 37: 'ض',
 38: 'ژ'}

In [73]:
object1.char_to_index("سلام")

[19, 22, 6, 13]

In [74]:
train_encode=np.array(object1.char_to_index(cleaned_data))

In [75]:
len(train_encode)

174011905

In [76]:
train_encode=train_encode[:len(train_encode)//5]

In [77]:
len(train_encode)

34802381

In [78]:
object1.index_to_char([19, 22,  6, 13])

'سلام'

In [79]:
file1 = open('char2index.txt', 'w',encoding="utf-8")
for key in char2index.keys():
    st=str(key+" "+str(char2index[key])+"\n")
    file1.write(st)
file1.close()

In [80]:
file2 = open('index2char.txt', 'w',encoding="utf-8")
for key in index2char.keys():
    st=str(str(key)+" "+index2char[key]+"\n")
    file2.write(st)
file2.close()

In [81]:
cleaned_test=object1.clean(test)

In [82]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
from keras.utils import np_utils
import math
from datasets import load_metric

In [89]:
class define_model(nn.Module):
    def __init__(self, n_chars=39, n_hidden=64, n_layers=1):
        super().__init__()
        self.chars = n_chars
        self.n_hidden = n_hidden
        self.n_layers = n_layers
        
        self.lstm = nn.LSTM(self.chars, n_hidden, n_layers, batch_first=True)
        self.lin = nn.Linear(n_hidden, self.chars)
        
    def forward(self, x, ch):
        output, ch = self.lstm(x, ch)
        out = output.contiguous().view(-1, self.n_hidden)
        out = self.lin(out)
        return out, ch
        
    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        c=weight.new(self.n_layers, batch_size, self.n_hidden).zero_()
        h=weight.new(self.n_layers, batch_size, self.n_hidden).zero_()
        ch = (c,h)
        return ch

In [90]:
model=define_model(unique_chars,n_hidden=64,n_layers=1)
model

define_model(
  (lstm): LSTM(39, 64, batch_first=True)
  (lin): Linear(in_features=64, out_features=39, bias=True)
)

In [91]:
class train_char_LSTM(define_model):
    def __init__(self,data,model, epochs, batch_size, seq_length, valid =0.1):
        define_model.__init__(self)
        self.data=data
        self.model=model
        self.epochs=epochs
        self.batch_size=batch_size
        self.seq_length=seq_length
        self.valid=valid
        self.fit=self.train_char_LSTM_function()

    def x_y(self,arr, batch_size, seq_length):
        num_batches = len(arr)//(batch_size * seq_length)
        arr = arr[:num_batches * (batch_size * seq_length)]
        arr = arr.reshape((batch_size, -1))
        
        for n in range(0, arr.shape[1], seq_length):
            x = arr[:, n:n+seq_length]
            y = np.zeros(np.shape(x))
            y[:,:-1]=x[:,1:]
            if(n+seq_length<arr.shape[1]-1):
                y[:,-1] =arr[:, n+seq_length]
            else:
                y[:,-1] = arr[:,0]
            yield x, y
    def train_char_LSTM_function(self):
        self.model.train()

        opt = torch.optim.Adam(self.model.parameters())
        criterion = nn.CrossEntropyLoss()
        val = int(len(self.data)*(1-self.valid))
        data_train, data_val = self.data[:val], self.data[val:]
        step = 0
        for e in range(self.epochs):
            ch = self.model.init_hidden(self.batch_size)

            for x,y in self.x_y(data_train, self.batch_size, self.seq_length):
                step += 1
                    
                x = np_utils.to_categorical(x, self.model.chars)
                X, Y = torch.from_numpy(x), torch.from_numpy(y)
                Y = Y.type(torch.LongTensor)
                ch = tuple([each.data for each in ch])
                
                self.model.zero_grad()
                output, ch = self.model(X, ch)
                loss = criterion(output, Y.view(self.batch_size*self.seq_length))
                loss.backward()
                    
                nn.utils.clip_grad_norm_(model.parameters(), 5)
                opt.step()
                if step % 10 == 0:
                    val_ch = self.model.init_hidden(self.batch_size)
                    val_losses = []
                    self.model.eval()
                    for x,y in self.x_y(data_val, self.batch_size, self.seq_length):
                        X, Y = torch.from_numpy(np_utils.to_categorical(x, self.model.chars)), torch.from_numpy(y)
                        Y = Y.type(torch.LongTensor)
                        val_ch = tuple([each.data for each in val_ch])
                        
                        output, val_ch = self.model(X, val_ch)
                        val_loss = criterion(output, Y.view(self.batch_size* self.seq_length))
                        val_losses.append(val_loss.item())
                        
                    self.model.train()
                    print('Epoch: ',e+1, '    Step: ' ,step, '    Loss: ' ,loss.item(),'    Val Loss: ',np.mean(val_losses))

In [92]:
batch_size = 64
seq_length = 200
n_epochs = 2
train_char_LSTM(train_encode,model,n_epochs, batch_size, seq_length)

Epoch:  1     Step:  10     Loss:  3.5748071670532227     Val Loss:  3.5678419072689604
Epoch:  1     Step:  20     Loss:  3.383718490600586     Val Loss:  3.3467685120572024
Epoch:  1     Step:  30     Loss:  2.826709508895874     Val Loss:  2.8421255442489115
Epoch:  1     Step:  40     Loss:  2.8102407455444336     Val Loss:  2.7972983724516696
Epoch:  1     Step:  50     Loss:  2.763270616531372     Val Loss:  2.772118237625629
Epoch:  1     Step:  60     Loss:  2.7994377613067627     Val Loss:  2.7685511112213135
Epoch:  1     Step:  70     Loss:  2.7928578853607178     Val Loss:  2.7665173866652033
Epoch:  1     Step:  80     Loss:  2.774726629257202     Val Loss:  2.7656276384402907
Epoch:  1     Step:  90     Loss:  2.7852818965911865     Val Loss:  2.7631237084575244
Epoch:  1     Step:  100     Loss:  2.7549853324890137     Val Loss:  2.7588923170997646
Epoch:  1     Step:  110     Loss:  2.756500244140625     Val Loss:  2.757543890238688
Epoch:  1     Step:  120     Loss:  2

Epoch:  1     Step:  950     Loss:  2.318171977996826     Val Loss:  2.363339813872897
Epoch:  1     Step:  960     Loss:  2.330045700073242     Val Loss:  2.3582532757762613
Epoch:  1     Step:  970     Loss:  2.2981860637664795     Val Loss:  2.3591825152675163
Epoch:  1     Step:  980     Loss:  2.3049683570861816     Val Loss:  2.3594690328154617
Epoch:  1     Step:  990     Loss:  2.28564453125     Val Loss:  2.356889406253491
Epoch:  1     Step:  1000     Loss:  2.3409605026245117     Val Loss:  2.3556800671609124
Epoch:  1     Step:  1010     Loss:  2.3219871520996094     Val Loss:  2.35041232566552
Epoch:  1     Step:  1020     Loss:  2.333200693130493     Val Loss:  2.349177710684463
Epoch:  1     Step:  1030     Loss:  2.231487512588501     Val Loss:  2.3503556840974027
Epoch:  1     Step:  1040     Loss:  2.2092602252960205     Val Loss:  2.3490915272068715
Epoch:  1     Step:  1050     Loss:  2.226003408432007     Val Loss:  2.3427321198241735
Epoch:  1     Step:  1060     

Epoch:  1     Step:  1880     Loss:  2.2054712772369385     Val Loss:  2.2171357874500797
Epoch:  1     Step:  1890     Loss:  2.207995891571045     Val Loss:  2.2153989837618333
Epoch:  1     Step:  1900     Loss:  2.163198947906494     Val Loss:  2.2140541437367234
Epoch:  1     Step:  1910     Loss:  2.139845609664917     Val Loss:  2.212789130826718
Epoch:  1     Step:  1920     Loss:  2.2220990657806396     Val Loss:  2.215051567422508
Epoch:  1     Step:  1930     Loss:  2.209148406982422     Val Loss:  2.2142950248014444
Epoch:  1     Step:  1940     Loss:  2.2010626792907715     Val Loss:  2.2114265035439242
Epoch:  1     Step:  1950     Loss:  2.170013189315796     Val Loss:  2.213005703753651
Epoch:  1     Step:  1960     Loss:  2.1082963943481445     Val Loss:  2.2124297997168507
Epoch:  1     Step:  1970     Loss:  2.156310558319092     Val Loss:  2.209234683715989
Epoch:  1     Step:  1980     Loss:  2.1371302604675293     Val Loss:  2.2100532732326608
Epoch:  1     Step: 

Epoch:  2     Step:  2810     Loss:  2.083106756210327     Val Loss:  2.1346280574798584
Epoch:  2     Step:  2820     Loss:  2.132993221282959     Val Loss:  2.1355508526312907
Epoch:  2     Step:  2830     Loss:  2.1685357093811035     Val Loss:  2.1352944224523003
Epoch:  2     Step:  2840     Loss:  2.0115866661071777     Val Loss:  2.134691885036736
Epoch:  2     Step:  2850     Loss:  1.9974597692489624     Val Loss:  2.132617625803085
Epoch:  2     Step:  2860     Loss:  2.009526252746582     Val Loss:  2.1335798189648845
Epoch:  2     Step:  2870     Loss:  2.046086072921753     Val Loss:  2.153644976140828
Epoch:  2     Step:  2880     Loss:  2.029420852661133     Val Loss:  2.154466551608265
Epoch:  2     Step:  2890     Loss:  2.0297975540161133     Val Loss:  2.1351396518439825
Epoch:  2     Step:  2900     Loss:  2.0549521446228027     Val Loss:  2.1366304638640905
Epoch:  2     Step:  2910     Loss:  1.9830933809280396     Val Loss:  2.1298450790208205
Epoch:  2     Step:

Epoch:  2     Step:  3730     Loss:  1.9938277006149292     Val Loss:  2.0683054158608414
Epoch:  2     Step:  3740     Loss:  2.0107367038726807     Val Loss:  2.0708977903387202
Epoch:  2     Step:  3750     Loss:  2.017223358154297     Val Loss:  2.072692651590298
Epoch:  2     Step:  3760     Loss:  1.962009072303772     Val Loss:  2.0707427276456487
Epoch:  2     Step:  3770     Loss:  2.0024523735046387     Val Loss:  2.069583615253772
Epoch:  2     Step:  3780     Loss:  2.042965888977051     Val Loss:  2.069180068054762
Epoch:  2     Step:  3790     Loss:  2.000006675720215     Val Loss:  2.06710808875376
Epoch:  2     Step:  3800     Loss:  1.9810374975204468     Val Loss:  2.069005717210664
Epoch:  2     Step:  3810     Loss:  1.9748188257217407     Val Loss:  2.066271823710621
Epoch:  2     Step:  3820     Loss:  2.0284481048583984     Val Loss:  2.067954151392863
Epoch:  2     Step:  3830     Loss:  1.9809132814407349     Val Loss:  2.0668240776801023
Epoch:  2     Step:  3

Epoch:  2     Step:  4650     Loss:  1.7785124778747559     Val Loss:  2.0099667152355516
Epoch:  2     Step:  4660     Loss:  1.8740698099136353     Val Loss:  2.009033556354002
Epoch:  2     Step:  4670     Loss:  1.8727885484695435     Val Loss:  2.007118551493571
Epoch:  2     Step:  4680     Loss:  1.8183097839355469     Val Loss:  2.00494027577643
Epoch:  2     Step:  4690     Loss:  1.8707143068313599     Val Loss:  2.0058765956836435
Epoch:  2     Step:  4700     Loss:  1.94551420211792     Val Loss:  2.003653406656976
Epoch:  2     Step:  4710     Loss:  1.9345933198928833     Val Loss:  2.002163544792091
Epoch:  2     Step:  4720     Loss:  1.928596019744873     Val Loss:  2.0027623783618322
Epoch:  2     Step:  4730     Loss:  1.9825820922851562     Val Loss:  2.003215769120248
Epoch:  2     Step:  4740     Loss:  1.9110381603240967     Val Loss:  2.005485419857546
Epoch:  2     Step:  4750     Loss:  1.894621729850769     Val Loss:  2.002269489738774
Epoch:  2     Step:  47

train_char_LSTM(
  (lstm): LSTM(39, 64, batch_first=True)
  (lin): Linear(in_features=64, out_features=39, bias=True)
  (model): define_model(
    (lstm): LSTM(39, 64, batch_first=True)
    (lin): Linear(in_features=64, out_features=39, bias=True)
  )
)

In [205]:
class LanguageModel():
    def __init__(self,model):
        self.model=model
    
    def get_next_states_and_output(self, char, h):
        x = np.array([object1.char_to_index(char)])
        x = np_utils.to_categorical(x, self.model.chars)
        X = torch.from_numpy(x)
        h = tuple([each.data for each in h])
        h=(h[0][0],h[1][0])
        out, h = self.model(X, h)
        return out,h
    
    def convert_prefix_to_hiddens(self,string):
        h = self.model.init_hidden(1)
        ch1=list(string)[0]
        out,h = self.get_next_states_and_output(ch1, h)
        for ch in string[1:]:
            x = np.array([object1.char_to_index(ch)])
            x = np_utils.to_categorical(x, self.model.chars)
            X = torch.from_numpy(x)
            h = tuple([each.data for each in h])
            out, h = self.model(X, h)
        return out,h
    
    def get_probs(self,string):
        out,h=self.convert_prefix_to_hiddens(string)
        p = F.softmax(out, dim=1).data
        return p[0]
    
    def get_next_char(self,string):
        p=self.get_probs(string)
        p=p.numpy()
        m=np.max(p)
        tops=np.where(p == m)
        top_ch=np.random.choice(tops[0])
        char=object1.index_to_char([int(top_ch)])
        return char
    
    def generate_text(self,string,t):
        char=""
        while ((char!='e') and (len(string)!=t)) :
            char=self.get_next_char(string)
            string+=char
        if char!='e':
            string=string+'e'
        return string
    
    def get_overall_prob(self,jomle):
        sum=0
        for i in range(len(jomle)-1):
            ci=object1.char_to_index(jomle[i+1])
            p=self.get_probs(jomle[:i+1])
            sum+=math.log(p[ci])
        return sum
    
    def evaluate_per(self,test,t):
        perplexity=[]
        for st in test:
            s=self.generate_text(st[:25],t)
            log_li = self.get_overall_prob(s)
            n=len(s)
            perplexity.append((1/log_li)**(1/n))
        return perplexity
            
    def evaluate_cer(self,test,t):
        metric = load_metric("cer")
        cer=[]
        for st in test:
            s=self.generate_text(st[:25],t)
            cer.append(metric.compute(predictions=[st],references=[s]))
        return cer

In [206]:
object2=LanguageModel(model)

In [184]:
h = model.init_hidden(1)
object2.get_next_states_and_output('س',h)

(tensor([[-0.2618,  0.2962,  0.2889,  0.7344, -0.5939, -0.6479,  0.4767, -0.1893,
          -1.1483,  0.1383,  0.6053, -0.6619,  1.0502,  0.6708,  0.6455, -0.8529,
           0.8330, -0.0360, -0.3340, -0.7415, -0.3925,  0.6459,  0.0709,  0.4111,
          -0.7946, -1.1396, -0.3351, -0.2421, -0.6508, -1.8842, -0.4465, -1.5834,
          -0.8201, -0.7242, -0.6079,  0.3743, -0.5391, -0.5540, -0.7621]],
        grad_fn=<AddmmBackward0>),
 (tensor([[ 0.1239,  0.1934,  0.1039, -0.0050, -0.0463, -0.1453, -0.0010, -0.3334,
           -0.0445, -0.2544, -0.2948, -0.2470, -0.1530, -0.2130, -0.0070, -0.1014,
            0.0195,  0.0890, -0.0058, -0.0936, -0.0923, -0.2085,  0.0559, -0.1162,
            0.2006,  0.1026,  0.0582,  0.1640,  0.0224,  0.2214,  0.0591,  0.3246,
           -0.1899, -0.1614,  0.2694, -0.0749,  0.0246,  0.0483, -0.1896, -0.3714,
           -0.0973, -0.1411, -0.0712, -0.1289, -0.0063,  0.0758,  0.1837,  0.0367,
            0.0779,  0.0579,  0.1554,  0.3491, -0.1090,  0.1337,

In [185]:
object2.convert_prefix_to_hiddens('خبر')

(tensor([[-2.8498,  1.3883,  0.1345,  0.4400,  1.2954, -1.8405,  3.1859, -1.0102,
          -0.3491,  0.4257,  1.3518, -0.2608,  0.5192,  0.0740,  0.8325, -1.9273,
           0.8334,  0.5140, -0.6390, -0.1142, -2.3563, -0.8019, -3.2859, -1.7468,
          -0.6209, -1.4269, -1.6669, -1.2473, -0.8623, -0.0334, -1.7170, -2.1268,
          -2.7260, -3.1840, -1.2307, -1.9931, -0.9225,  0.2777, -0.3095]],
        grad_fn=<AddmmBackward0>),
 (tensor([[-0.2361,  0.2979, -0.1761, -0.3015, -0.0339,  0.0682,  0.1516, -0.3534,
           -0.0465,  0.0832, -0.2580, -0.5557, -0.1383,  0.3935,  0.2188,  0.0253,
           -0.3899,  0.2730, -0.3552, -0.3162,  0.1453,  0.4416, -0.0137,  0.6815,
           -0.3440,  0.3138,  0.0282,  0.4383,  0.0462,  0.2739,  0.1025,  0.1225,
           -0.3782, -0.1679,  0.1281, -0.5005, -0.0223,  0.0855, -0.0965, -0.1659,
            0.1086, -0.0272,  0.2630,  0.2025, -0.3907,  0.3526, -0.1661,  0.1332,
           -0.0096, -0.0536, -0.0014,  0.2942,  0.1885,  0.0368,

In [186]:
object2.get_probs('سلا')

tensor([0.0009, 0.0126, 0.0412, 0.0423, 0.0082, 0.0976, 0.0049, 0.0206, 0.0185,
        0.0075, 0.0904, 0.0167, 0.0398, 0.1794, 0.0238, 0.0069, 0.1058, 0.0768,
        0.0061, 0.0500, 0.0185, 0.0157, 0.0173, 0.0080, 0.0202, 0.0072, 0.0208,
        0.0098, 0.0003, 0.0030, 0.0092, 0.0022, 0.0017, 0.0027, 0.0028, 0.0010,
        0.0016, 0.0040, 0.0038])

In [187]:
object2.get_probs('به نقل از برخی')

tensor([4.2865e-07, 3.5305e-01, 2.9995e-02, 1.3400e-03, 7.7936e-03, 4.4035e-04,
        1.2312e-01, 7.7260e-02, 7.5201e-03, 2.6684e-03, 1.4166e-01, 1.3496e-03,
        1.8029e-02, 3.4449e-02, 6.2117e-03, 9.1722e-04, 1.1950e-01, 2.7329e-03,
        3.1842e-03, 1.2941e-02, 7.9020e-04, 5.5540e-03, 2.6035e-02, 6.5666e-03,
        4.2592e-03, 1.2096e-03, 4.1886e-03, 5.1277e-04, 1.0644e-03, 5.7085e-04,
        3.2656e-04, 3.1647e-05, 1.8485e-04, 1.9667e-04, 2.0411e-03, 1.3440e-04,
        1.5619e-04, 1.6089e-04, 1.8515e-03])

In [188]:
object2.get_probs('گروه فرهنگی')

tensor([3.5148e-06, 9.4167e-01, 1.1249e-03, 3.9070e-03, 1.5269e-03, 2.0151e-03,
        7.2664e-03, 3.6727e-03, 4.2653e-03, 1.7606e-05, 1.1338e-02, 1.5287e-05,
        1.4185e-03, 1.4213e-03, 9.6226e-03, 4.1220e-04, 1.9859e-03, 5.8200e-05,
        3.0333e-04, 1.6511e-03, 1.2145e-05, 2.5430e-03, 7.1499e-04, 2.1689e-06,
        5.9694e-05, 3.1474e-04, 3.1381e-04, 4.1492e-05, 1.6529e-03, 1.1092e-05,
        1.1880e-05, 3.2788e-06, 2.4236e-05, 3.1695e-06, 1.1099e-06, 1.6137e-05,
        5.4827e-04, 2.7151e-05, 5.4928e-06])

In [189]:
object2.get_next_char('سلا')

'م'

In [190]:
object2.get_next_char('به گزارش خب')

'ر'

In [191]:
object2.get_next_char('گروه فرهنگی باشگا')

'ه'

In [192]:
object2.generate_text('به گزارش',30)

'به گزارش به گزارش خبرنگار خبرنe'

In [193]:
object2.generate_text('گروه فرهنگی',50)

'گروه فرهنگی باشگاه خبرنگاران جوان                 e'

In [194]:
object2.generate_text('هنرمند پیشکسوت و فر',30)

'هنرمند پیشکسوت و فرهنگ        e'

In [212]:
object2.get_overall_prob('گزارش')

-6.085223840054648

In [213]:
object2.get_overall_prob('یکی از قوانین حقوق بشر آزادی بیان است')

-76.88412112928302

In [214]:
object2.get_overall_prob('از ویژگی های بارز این دوره از جشنواره حضور هنرمندان همدانی در بخش داوری و بازبینی آثار است')

-146.37933382628955

In [208]:
object2.evaluate_per(cleaned_test["text"][:200],50)

[(0.9257022583119154+0.057095360962304026j),
 (0.9175506224774355+0.05659258527365916j),
 (0.9150138132101682+0.05643612023373231j),
 (0.9326044354511496+0.05752107267646682j),
 (0.9269166822070979+0.0571702640642832j),
 (0.919086459853511+0.05668731248057592j),
 (0.9381521571674787+0.057863244439653225j),
 (0.9316788050126793+0.057463981745200725j),
 (0.9381521571674787+0.057863244439653225j),
 (0.9119449813369093+0.056246841162667j),
 (0.9381521571674787+0.057863244439653225j),
 (0.9327251581041547+0.057528518594836105j),
 (0.9153625452532311+0.05645762928990995j),
 (0.9261037621281352+0.05712012487003891j),
 (0.9238698690550844+0.056982343061458676j),
 (0.912201921023886+0.056262688660112053j),
 (0.9308237359664278+0.057411242891638396j),
 (0.928877924164057+0.05729122932764034j),
 (0.9282084401433651+0.05724993696664988j),
 (0.9210440003425638+0.056808049445207086j),
 (0.9154482069741913+0.05646291272401088j),
 (0.9308237359664278+0.057411242891638396j),
 (0.9178247638719123+0.0566

In [209]:
object2.evaluate_cer(cleaned_test["text"][:200],50)

Using the latest cached version of the module from C:\Users\Melika\.cache\huggingface\modules\datasets_modules\metrics\cer\46482e3826224451c26c9b51d8d193d38a4226daab693df497d2e397b623274e (last modified on Sat May 28 01:13:19 2022) since it couldn't be found locally at cer, or remotely on the Hugging Face Hub.


[22.288888888888888,
 24.93548387096774,
 21.94,
 46.977777777777774,
 197.11764705882354,
 41.111111111111114,
 19.5,
 189.63333333333333,
 72.5,
 14.877551020408163,
 24.705882352941178,
 37.78431372549019,
 9.78,
 5.254901960784314,
 14.411764705882353,
 18.431372549019606,
 33.588235294117645,
 32.80392156862745,
 14.901960784313726,
 37.61538461538461,
 18.34,
 35.76470588235294,
 33.16,
 15.941176470588236,
 58.529411764705884,
 62.35294117647059,
 41.65217391304348,
 56.0,
 147.8235294117647,
 21.541666666666668,
 48.12244897959184,
 35.470588235294116,
 68.01960784313725,
 114.54,
 77.2156862745098,
 23.313725490196077,
 33.205882352941174,
 8.254901960784315,
 19.92156862745098,
 20.06896551724138,
 30.08823529411765,
 171.80392156862746,
 18.333333333333332,
 13.88,
 53.21739130434783,
 18.323529411764707,
 10.411764705882353,
 152.5686274509804,
 14.176470588235293,
 6.176470588235294,
 6.0588235294117645,
 30.98,
 27.470588235294116,
 90.25490196078431,
 188.76470588235293,